#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice_trm.h>

/* ISR */
#define ISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR__INTC_MASK 0x10000u
#define ISR__INTC_NUMBER 16u
#define ISR__INTC_PRIOR_MASK 0xC0u
#define ISR__INTC_PRIOR_NUM 3u
#define ISR__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* LED */
#define LED__0__DM__MASK 0x1C0000u
#define LED__0__DM__SHIFT 18
#define LED__0__DR CYREG_PRT1_DR
#define LED__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define LED__0__HSIOM_MASK 0x0F000000u
#define LED__0__HSIOM_SHIFT 24u
#define LED__0__INTCFG CYREG_PRT1_INTCFG
#define LED__0__INTSTAT CYREG_PRT1_INTSTAT
#define LED__0__MASK 0x40u
#define LED__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LED__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LED__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LED__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LED__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LED__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LED__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LED__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LED__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LED__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LED__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LED__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LED__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LED__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LED__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LED__0__PC CYREG_PRT1_PC
#define LED__0__PC2 CYREG_PRT1_PC2
#define LED__0__PORT 1u
#define LED__0__PS CYREG_PRT1_PS
#define LED__0__SHIFT 6
#define LED__DR CYREG_PRT1_DR
#define LED__INTCFG CYREG_PRT1_INTCFG
#define LED__INTSTAT CYREG_PRT1_INTSTAT
#define LED__MASK 0x40u
#define LED__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LED__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LED__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LED__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LED__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LED__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LED__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LED__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LED__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LED__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LED__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LED__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LED__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LED__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LED__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LED__PC CYREG_PRT1_PC
#define LED__PC2 CYREG_PRT1_PC2
#define LED__PORT 1u
#define LED__PS CYREG_PRT1_PS
#define LED__SHIFT 6

/* CONTROL */
#define CONTROL__0__DM__MASK 0x07u
#define CONTROL__0__DM__SHIFT 0
#define CONTROL__0__DR CYREG_PRT2_DR
#define CONTROL__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define CONTROL__0__HSIOM_MASK 0x0000000Fu
#define CONTROL__0__HSIOM_SHIFT 0u
#define CONTROL__0__INTCFG CYREG_PRT2_INTCFG
#define CONTROL__0__INTSTAT CYREG_PRT2_INTSTAT
#define CONTROL__0__MASK 0x01u
#define CONTROL__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define CONTROL__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define CONTROL__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define CONTROL__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define CONTROL__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define CONTROL__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define CONTROL__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define CONTROL__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define CONTROL__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define CONTROL__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define CONTROL__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define CONTROL__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define CONTROL__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define CONTROL__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define CONTROL__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define CONTROL__0__PC CYREG_PRT2_PC
#define CONTROL__0__PC2 CYREG_PRT2_PC2
#define CONTROL__0__PORT 2u
#define CONTROL__0__PS CYREG_PRT2_PS
#define CONTROL__0__SHIFT 0
#define CONTROL__DR CYREG_PRT2_DR
#define CONTROL__INTCFG CYREG_PRT2_INTCFG
#define CONTROL__INTSTAT CYREG_PRT2_INTSTAT
#define CONTROL__MASK 0x01u
#define CONTROL__PA__CFG0 CYREG_UDB_PA2_CFG0
#define CONTROL__PA__CFG1 CYREG_UDB_PA2_CFG1
#define CONTROL__PA__CFG10 CYREG_UDB_PA2_CFG10
#define CONTROL__PA__CFG11 CYREG_UDB_PA2_CFG11
#define CONTROL__PA__CFG12 CYREG_UDB_PA2_CFG12
#define CONTROL__PA__CFG13 CYREG_UDB_PA2_CFG13
#define CONTROL__PA__CFG14 CYREG_UDB_PA2_CFG14
#define CONTROL__PA__CFG2 CYREG_UDB_PA2_CFG2
#define CONTROL__PA__CFG3 CYREG_UDB_PA2_CFG3
#define CONTROL__PA__CFG4 CYREG_UDB_PA2_CFG4
#define CONTROL__PA__CFG5 CYREG_UDB_PA2_CFG5
#define CONTROL__PA__CFG6 CYREG_UDB_PA2_CFG6
#define CONTROL__PA__CFG7 CYREG_UDB_PA2_CFG7
#define CONTROL__PA__CFG8 CYREG_UDB_PA2_CFG8
#define CONTROL__PA__CFG9 CYREG_UDB_PA2_CFG9
#define CONTROL__PC CYREG_PRT2_PC
#define CONTROL__PC2 CYREG_PRT2_PC2
#define CONTROL__PORT 2u
#define CONTROL__PS CYREG_PRT2_PS
#define CONTROL__SHIFT 0

/* Clock_4 */
#define Clock_4__DIVIDER_MASK 0x0000FFFFu
#define Clock_4__ENABLE CYREG_CLK_DIVIDER_A00
#define Clock_4__ENABLE_MASK 0x80000000u
#define Clock_4__MASK 0x80000000u
#define Clock_4__REGISTER CYREG_CLK_DIVIDER_A00

/* Timer_1_cy_m0s8_tcpwm_1 */
#define Timer_1_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT0_CC
#define Timer_1_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT0_CC_BUFF
#define Timer_1_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT0_COUNTER
#define Timer_1_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT0_CTRL
#define Timer_1_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT0_INTR
#define Timer_1_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT0_INTR_MASK
#define Timer_1_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT0_INTR_MASKED
#define Timer_1_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT0_INTR_SET
#define Timer_1_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT0_PERIOD
#define Timer_1_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT0_PERIOD_BUFF
#define Timer_1_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT0_STATUS
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x01u
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 0
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x100u
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 8
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x1000000u
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 24
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x10000u
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 16
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x01u
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 0
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x01u
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 0
#define Timer_1_cy_m0s8_tcpwm_1__TCPWM_NUMBER 0u
#define Timer_1_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT0_TR_CTRL0
#define Timer_1_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT0_TR_CTRL1
#define Timer_1_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT0_TR_CTRL2

/* Camera_Pan */
#define Camera_Pan__0__DM__MASK 0x38000u
#define Camera_Pan__0__DM__SHIFT 15
#define Camera_Pan__0__DR CYREG_PRT0_DR
#define Camera_Pan__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Camera_Pan__0__HSIOM_MASK 0x00F00000u
#define Camera_Pan__0__HSIOM_SHIFT 20u
#define Camera_Pan__0__INTCFG CYREG_PRT0_INTCFG
#define Camera_Pan__0__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Pan__0__MASK 0x20u
#define Camera_Pan__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Camera_Pan__0__OUT_SEL_SHIFT 10u
#define Camera_Pan__0__OUT_SEL_VAL 2u
#define Camera_Pan__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Pan__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Pan__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Pan__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Pan__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Pan__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Pan__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Pan__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Pan__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Pan__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Pan__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Pan__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Pan__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Pan__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Pan__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Pan__0__PC CYREG_PRT0_PC
#define Camera_Pan__0__PC2 CYREG_PRT0_PC2
#define Camera_Pan__0__PORT 0u
#define Camera_Pan__0__PS CYREG_PRT0_PS
#define Camera_Pan__0__SHIFT 5
#define Camera_Pan__DR CYREG_PRT0_DR
#define Camera_Pan__INTCFG CYREG_PRT0_INTCFG
#define Camera_Pan__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Pan__MASK 0x20u
#define Camera_Pan__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Pan__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Pan__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Pan__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Pan__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Pan__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Pan__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Pan__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Pan__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Pan__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Pan__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Pan__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Pan__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Pan__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Pan__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Pan__PC CYREG_PRT0_PC
#define Camera_Pan__PC2 CYREG_PRT0_PC2
#define Camera_Pan__PORT 0u
#define Camera_Pan__PS CYREG_PRT0_PS
#define Camera_Pan__SHIFT 5

/* Camera_Pan_Backup */
#define Camera_Pan_Backup__0__DM__MASK 0x1C0000u
#define Camera_Pan_Backup__0__DM__SHIFT 18
#define Camera_Pan_Backup__0__DR CYREG_PRT0_DR
#define Camera_Pan_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Camera_Pan_Backup__0__HSIOM_MASK 0x0F000000u
#define Camera_Pan_Backup__0__HSIOM_SHIFT 24u
#define Camera_Pan_Backup__0__INTCFG CYREG_PRT0_INTCFG
#define Camera_Pan_Backup__0__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Pan_Backup__0__MASK 0x40u
#define Camera_Pan_Backup__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Pan_Backup__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Pan_Backup__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Pan_Backup__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Pan_Backup__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Pan_Backup__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Pan_Backup__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Pan_Backup__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Pan_Backup__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Pan_Backup__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Pan_Backup__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Pan_Backup__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Pan_Backup__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Pan_Backup__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Pan_Backup__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Pan_Backup__0__PC CYREG_PRT0_PC
#define Camera_Pan_Backup__0__PC2 CYREG_PRT0_PC2
#define Camera_Pan_Backup__0__PORT 0u
#define Camera_Pan_Backup__0__PS CYREG_PRT0_PS
#define Camera_Pan_Backup__0__SHIFT 6
#define Camera_Pan_Backup__DR CYREG_PRT0_DR
#define Camera_Pan_Backup__INTCFG CYREG_PRT0_INTCFG
#define Camera_Pan_Backup__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Pan_Backup__MASK 0x40u
#define Camera_Pan_Backup__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Pan_Backup__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Pan_Backup__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Pan_Backup__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Pan_Backup__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Pan_Backup__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Pan_Backup__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Pan_Backup__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Pan_Backup__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Pan_Backup__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Pan_Backup__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Pan_Backup__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Pan_Backup__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Pan_Backup__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Pan_Backup__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Pan_Backup__PC CYREG_PRT0_PC
#define Camera_Pan_Backup__PC2 CYREG_PRT0_PC2
#define Camera_Pan_Backup__PORT 0u
#define Camera_Pan_Backup__PS CYREG_PRT0_PS
#define Camera_Pan_Backup__SHIFT 6

/* Camera_Pan_MCU */
#define Camera_Pan_MCU__0__DM__MASK 0xE00000u
#define Camera_Pan_MCU__0__DM__SHIFT 21
#define Camera_Pan_MCU__0__DR CYREG_PRT0_DR
#define Camera_Pan_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Camera_Pan_MCU__0__HSIOM_MASK 0xF0000000u
#define Camera_Pan_MCU__0__HSIOM_SHIFT 28u
#define Camera_Pan_MCU__0__INTCFG CYREG_PRT0_INTCFG
#define Camera_Pan_MCU__0__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Pan_MCU__0__MASK 0x80u
#define Camera_Pan_MCU__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Pan_MCU__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Pan_MCU__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Pan_MCU__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Pan_MCU__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Pan_MCU__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Pan_MCU__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Pan_MCU__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Pan_MCU__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Pan_MCU__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Pan_MCU__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Pan_MCU__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Pan_MCU__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Pan_MCU__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Pan_MCU__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Pan_MCU__0__PC CYREG_PRT0_PC
#define Camera_Pan_MCU__0__PC2 CYREG_PRT0_PC2
#define Camera_Pan_MCU__0__PORT 0u
#define Camera_Pan_MCU__0__PS CYREG_PRT0_PS
#define Camera_Pan_MCU__0__SHIFT 7
#define Camera_Pan_MCU__DR CYREG_PRT0_DR
#define Camera_Pan_MCU__INTCFG CYREG_PRT0_INTCFG
#define Camera_Pan_MCU__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Pan_MCU__MASK 0x80u
#define Camera_Pan_MCU__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Pan_MCU__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Pan_MCU__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Pan_MCU__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Pan_MCU__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Pan_MCU__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Pan_MCU__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Pan_MCU__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Pan_MCU__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Pan_MCU__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Pan_MCU__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Pan_MCU__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Pan_MCU__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Pan_MCU__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Pan_MCU__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Pan_MCU__PC CYREG_PRT0_PC
#define Camera_Pan_MCU__PC2 CYREG_PRT0_PC2
#define Camera_Pan_MCU__PORT 0u
#define Camera_Pan_MCU__PS CYREG_PRT0_PS
#define Camera_Pan_MCU__SHIFT 7

/* Drive_Left */
#define Drive_Left__0__DM__MASK 0x07u
#define Drive_Left__0__DM__SHIFT 0
#define Drive_Left__0__DR CYREG_PRT1_DR
#define Drive_Left__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Drive_Left__0__HSIOM_MASK 0x0000000Fu
#define Drive_Left__0__HSIOM_SHIFT 0u
#define Drive_Left__0__INTCFG CYREG_PRT1_INTCFG
#define Drive_Left__0__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Left__0__MASK 0x01u
#define Drive_Left__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Drive_Left__0__OUT_SEL_SHIFT 0u
#define Drive_Left__0__OUT_SEL_VAL 0u
#define Drive_Left__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Left__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Left__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Left__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Left__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Left__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Left__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Left__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Left__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Left__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Left__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Left__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Left__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Left__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Left__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Left__0__PC CYREG_PRT1_PC
#define Drive_Left__0__PC2 CYREG_PRT1_PC2
#define Drive_Left__0__PORT 1u
#define Drive_Left__0__PS CYREG_PRT1_PS
#define Drive_Left__0__SHIFT 0
#define Drive_Left__DR CYREG_PRT1_DR
#define Drive_Left__INTCFG CYREG_PRT1_INTCFG
#define Drive_Left__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Left__MASK 0x01u
#define Drive_Left__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Left__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Left__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Left__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Left__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Left__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Left__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Left__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Left__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Left__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Left__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Left__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Left__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Left__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Left__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Left__PC CYREG_PRT1_PC
#define Drive_Left__PC2 CYREG_PRT1_PC2
#define Drive_Left__PORT 1u
#define Drive_Left__PS CYREG_PRT1_PS
#define Drive_Left__SHIFT 0

/* Drive_Left_Backup */
#define Drive_Left_Backup__0__DM__MASK 0x38u
#define Drive_Left_Backup__0__DM__SHIFT 3
#define Drive_Left_Backup__0__DR CYREG_PRT1_DR
#define Drive_Left_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Drive_Left_Backup__0__HSIOM_MASK 0x000000F0u
#define Drive_Left_Backup__0__HSIOM_SHIFT 4u
#define Drive_Left_Backup__0__INTCFG CYREG_PRT1_INTCFG
#define Drive_Left_Backup__0__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Left_Backup__0__MASK 0x02u
#define Drive_Left_Backup__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Left_Backup__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Left_Backup__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Left_Backup__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Left_Backup__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Left_Backup__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Left_Backup__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Left_Backup__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Left_Backup__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Left_Backup__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Left_Backup__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Left_Backup__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Left_Backup__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Left_Backup__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Left_Backup__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Left_Backup__0__PC CYREG_PRT1_PC
#define Drive_Left_Backup__0__PC2 CYREG_PRT1_PC2
#define Drive_Left_Backup__0__PORT 1u
#define Drive_Left_Backup__0__PS CYREG_PRT1_PS
#define Drive_Left_Backup__0__SHIFT 1
#define Drive_Left_Backup__DR CYREG_PRT1_DR
#define Drive_Left_Backup__INTCFG CYREG_PRT1_INTCFG
#define Drive_Left_Backup__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Left_Backup__MASK 0x02u
#define Drive_Left_Backup__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Left_Backup__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Left_Backup__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Left_Backup__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Left_Backup__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Left_Backup__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Left_Backup__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Left_Backup__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Left_Backup__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Left_Backup__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Left_Backup__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Left_Backup__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Left_Backup__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Left_Backup__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Left_Backup__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Left_Backup__PC CYREG_PRT1_PC
#define Drive_Left_Backup__PC2 CYREG_PRT1_PC2
#define Drive_Left_Backup__PORT 1u
#define Drive_Left_Backup__PS CYREG_PRT1_PS
#define Drive_Left_Backup__SHIFT 1

/* Drive_Left_MCU */
#define Drive_Left_MCU__0__DM__MASK 0x1C0u
#define Drive_Left_MCU__0__DM__SHIFT 6
#define Drive_Left_MCU__0__DR CYREG_PRT1_DR
#define Drive_Left_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Drive_Left_MCU__0__HSIOM_MASK 0x00000F00u
#define Drive_Left_MCU__0__HSIOM_SHIFT 8u
#define Drive_Left_MCU__0__INTCFG CYREG_PRT1_INTCFG
#define Drive_Left_MCU__0__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Left_MCU__0__MASK 0x04u
#define Drive_Left_MCU__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Left_MCU__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Left_MCU__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Left_MCU__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Left_MCU__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Left_MCU__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Left_MCU__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Left_MCU__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Left_MCU__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Left_MCU__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Left_MCU__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Left_MCU__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Left_MCU__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Left_MCU__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Left_MCU__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Left_MCU__0__PC CYREG_PRT1_PC
#define Drive_Left_MCU__0__PC2 CYREG_PRT1_PC2
#define Drive_Left_MCU__0__PORT 1u
#define Drive_Left_MCU__0__PS CYREG_PRT1_PS
#define Drive_Left_MCU__0__SHIFT 2
#define Drive_Left_MCU__DR CYREG_PRT1_DR
#define Drive_Left_MCU__INTCFG CYREG_PRT1_INTCFG
#define Drive_Left_MCU__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Left_MCU__MASK 0x04u
#define Drive_Left_MCU__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Left_MCU__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Left_MCU__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Left_MCU__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Left_MCU__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Left_MCU__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Left_MCU__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Left_MCU__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Left_MCU__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Left_MCU__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Left_MCU__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Left_MCU__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Left_MCU__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Left_MCU__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Left_MCU__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Left_MCU__PC CYREG_PRT1_PC
#define Drive_Left_MCU__PC2 CYREG_PRT1_PC2
#define Drive_Left_MCU__PORT 1u
#define Drive_Left_MCU__PS CYREG_PRT1_PS
#define Drive_Left_MCU__SHIFT 2

/* Camera_Tilt */
#define Camera_Tilt__0__DM__MASK 0x1C0u
#define Camera_Tilt__0__DM__SHIFT 6
#define Camera_Tilt__0__DR CYREG_PRT0_DR
#define Camera_Tilt__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Camera_Tilt__0__HSIOM_MASK 0x00000F00u
#define Camera_Tilt__0__HSIOM_SHIFT 8u
#define Camera_Tilt__0__INTCFG CYREG_PRT0_INTCFG
#define Camera_Tilt__0__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Tilt__0__MASK 0x04u
#define Camera_Tilt__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Camera_Tilt__0__OUT_SEL_SHIFT 4u
#define Camera_Tilt__0__OUT_SEL_VAL 2u
#define Camera_Tilt__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Tilt__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Tilt__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Tilt__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Tilt__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Tilt__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Tilt__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Tilt__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Tilt__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Tilt__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Tilt__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Tilt__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Tilt__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Tilt__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Tilt__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Tilt__0__PC CYREG_PRT0_PC
#define Camera_Tilt__0__PC2 CYREG_PRT0_PC2
#define Camera_Tilt__0__PORT 0u
#define Camera_Tilt__0__PS CYREG_PRT0_PS
#define Camera_Tilt__0__SHIFT 2
#define Camera_Tilt__DR CYREG_PRT0_DR
#define Camera_Tilt__INTCFG CYREG_PRT0_INTCFG
#define Camera_Tilt__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Tilt__MASK 0x04u
#define Camera_Tilt__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Tilt__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Tilt__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Tilt__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Tilt__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Tilt__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Tilt__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Tilt__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Tilt__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Tilt__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Tilt__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Tilt__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Tilt__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Tilt__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Tilt__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Tilt__PC CYREG_PRT0_PC
#define Camera_Tilt__PC2 CYREG_PRT0_PC2
#define Camera_Tilt__PORT 0u
#define Camera_Tilt__PS CYREG_PRT0_PS
#define Camera_Tilt__SHIFT 2

/* Camera_Tilt_Backup */
#define Camera_Tilt_Backup__0__DM__MASK 0xE00u
#define Camera_Tilt_Backup__0__DM__SHIFT 9
#define Camera_Tilt_Backup__0__DR CYREG_PRT0_DR
#define Camera_Tilt_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Camera_Tilt_Backup__0__HSIOM_MASK 0x0000F000u
#define Camera_Tilt_Backup__0__HSIOM_SHIFT 12u
#define Camera_Tilt_Backup__0__INTCFG CYREG_PRT0_INTCFG
#define Camera_Tilt_Backup__0__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Tilt_Backup__0__MASK 0x08u
#define Camera_Tilt_Backup__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Tilt_Backup__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Tilt_Backup__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Tilt_Backup__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Tilt_Backup__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Tilt_Backup__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Tilt_Backup__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Tilt_Backup__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Tilt_Backup__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Tilt_Backup__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Tilt_Backup__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Tilt_Backup__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Tilt_Backup__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Tilt_Backup__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Tilt_Backup__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Tilt_Backup__0__PC CYREG_PRT0_PC
#define Camera_Tilt_Backup__0__PC2 CYREG_PRT0_PC2
#define Camera_Tilt_Backup__0__PORT 0u
#define Camera_Tilt_Backup__0__PS CYREG_PRT0_PS
#define Camera_Tilt_Backup__0__SHIFT 3
#define Camera_Tilt_Backup__DR CYREG_PRT0_DR
#define Camera_Tilt_Backup__INTCFG CYREG_PRT0_INTCFG
#define Camera_Tilt_Backup__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Tilt_Backup__MASK 0x08u
#define Camera_Tilt_Backup__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Tilt_Backup__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Tilt_Backup__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Tilt_Backup__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Tilt_Backup__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Tilt_Backup__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Tilt_Backup__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Tilt_Backup__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Tilt_Backup__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Tilt_Backup__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Tilt_Backup__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Tilt_Backup__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Tilt_Backup__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Tilt_Backup__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Tilt_Backup__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Tilt_Backup__PC CYREG_PRT0_PC
#define Camera_Tilt_Backup__PC2 CYREG_PRT0_PC2
#define Camera_Tilt_Backup__PORT 0u
#define Camera_Tilt_Backup__PS CYREG_PRT0_PS
#define Camera_Tilt_Backup__SHIFT 3

/* Camera_Tilt_MCU */
#define Camera_Tilt_MCU__0__DM__MASK 0x7000u
#define Camera_Tilt_MCU__0__DM__SHIFT 12
#define Camera_Tilt_MCU__0__DR CYREG_PRT0_DR
#define Camera_Tilt_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Camera_Tilt_MCU__0__HSIOM_MASK 0x000F0000u
#define Camera_Tilt_MCU__0__HSIOM_SHIFT 16u
#define Camera_Tilt_MCU__0__INTCFG CYREG_PRT0_INTCFG
#define Camera_Tilt_MCU__0__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Tilt_MCU__0__MASK 0x10u
#define Camera_Tilt_MCU__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Tilt_MCU__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Tilt_MCU__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Tilt_MCU__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Tilt_MCU__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Tilt_MCU__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Tilt_MCU__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Tilt_MCU__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Tilt_MCU__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Tilt_MCU__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Tilt_MCU__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Tilt_MCU__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Tilt_MCU__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Tilt_MCU__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Tilt_MCU__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Tilt_MCU__0__PC CYREG_PRT0_PC
#define Camera_Tilt_MCU__0__PC2 CYREG_PRT0_PC2
#define Camera_Tilt_MCU__0__PORT 0u
#define Camera_Tilt_MCU__0__PS CYREG_PRT0_PS
#define Camera_Tilt_MCU__0__SHIFT 4
#define Camera_Tilt_MCU__DR CYREG_PRT0_DR
#define Camera_Tilt_MCU__INTCFG CYREG_PRT0_INTCFG
#define Camera_Tilt_MCU__INTSTAT CYREG_PRT0_INTSTAT
#define Camera_Tilt_MCU__MASK 0x10u
#define Camera_Tilt_MCU__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Camera_Tilt_MCU__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Camera_Tilt_MCU__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Camera_Tilt_MCU__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Camera_Tilt_MCU__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Camera_Tilt_MCU__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Camera_Tilt_MCU__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Camera_Tilt_MCU__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Camera_Tilt_MCU__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Camera_Tilt_MCU__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Camera_Tilt_MCU__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Camera_Tilt_MCU__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Camera_Tilt_MCU__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Camera_Tilt_MCU__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Camera_Tilt_MCU__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Camera_Tilt_MCU__PC CYREG_PRT0_PC
#define Camera_Tilt_MCU__PC2 CYREG_PRT0_PC2
#define Camera_Tilt_MCU__PORT 0u
#define Camera_Tilt_MCU__PS CYREG_PRT0_PS
#define Camera_Tilt_MCU__SHIFT 4

/* Drive_Right */
#define Drive_Right__0__DM__MASK 0xE00u
#define Drive_Right__0__DM__SHIFT 9
#define Drive_Right__0__DR CYREG_PRT1_DR
#define Drive_Right__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Drive_Right__0__HSIOM_MASK 0x0000F000u
#define Drive_Right__0__HSIOM_SHIFT 12u
#define Drive_Right__0__INTCFG CYREG_PRT1_INTCFG
#define Drive_Right__0__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Right__0__MASK 0x08u
#define Drive_Right__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Drive_Right__0__OUT_SEL_SHIFT 6u
#define Drive_Right__0__OUT_SEL_VAL 2u
#define Drive_Right__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Right__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Right__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Right__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Right__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Right__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Right__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Right__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Right__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Right__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Right__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Right__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Right__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Right__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Right__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Right__0__PC CYREG_PRT1_PC
#define Drive_Right__0__PC2 CYREG_PRT1_PC2
#define Drive_Right__0__PORT 1u
#define Drive_Right__0__PS CYREG_PRT1_PS
#define Drive_Right__0__SHIFT 3
#define Drive_Right__DR CYREG_PRT1_DR
#define Drive_Right__INTCFG CYREG_PRT1_INTCFG
#define Drive_Right__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Right__MASK 0x08u
#define Drive_Right__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Right__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Right__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Right__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Right__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Right__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Right__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Right__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Right__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Right__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Right__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Right__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Right__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Right__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Right__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Right__PC CYREG_PRT1_PC
#define Drive_Right__PC2 CYREG_PRT1_PC2
#define Drive_Right__PORT 1u
#define Drive_Right__PS CYREG_PRT1_PS
#define Drive_Right__SHIFT 3

/* Drive_Right_Backup */
#define Drive_Right_Backup__0__DM__MASK 0x7000u
#define Drive_Right_Backup__0__DM__SHIFT 12
#define Drive_Right_Backup__0__DR CYREG_PRT1_DR
#define Drive_Right_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Drive_Right_Backup__0__HSIOM_MASK 0x000F0000u
#define Drive_Right_Backup__0__HSIOM_SHIFT 16u
#define Drive_Right_Backup__0__INTCFG CYREG_PRT1_INTCFG
#define Drive_Right_Backup__0__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Right_Backup__0__MASK 0x10u
#define Drive_Right_Backup__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Right_Backup__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Right_Backup__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Right_Backup__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Right_Backup__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Right_Backup__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Right_Backup__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Right_Backup__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Right_Backup__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Right_Backup__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Right_Backup__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Right_Backup__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Right_Backup__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Right_Backup__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Right_Backup__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Right_Backup__0__PC CYREG_PRT1_PC
#define Drive_Right_Backup__0__PC2 CYREG_PRT1_PC2
#define Drive_Right_Backup__0__PORT 1u
#define Drive_Right_Backup__0__PS CYREG_PRT1_PS
#define Drive_Right_Backup__0__SHIFT 4
#define Drive_Right_Backup__DR CYREG_PRT1_DR
#define Drive_Right_Backup__INTCFG CYREG_PRT1_INTCFG
#define Drive_Right_Backup__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Right_Backup__MASK 0x10u
#define Drive_Right_Backup__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Right_Backup__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Right_Backup__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Right_Backup__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Right_Backup__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Right_Backup__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Right_Backup__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Right_Backup__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Right_Backup__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Right_Backup__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Right_Backup__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Right_Backup__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Right_Backup__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Right_Backup__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Right_Backup__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Right_Backup__PC CYREG_PRT1_PC
#define Drive_Right_Backup__PC2 CYREG_PRT1_PC2
#define Drive_Right_Backup__PORT 1u
#define Drive_Right_Backup__PS CYREG_PRT1_PS
#define Drive_Right_Backup__SHIFT 4

/* Drive_Right_MCU */
#define Drive_Right_MCU__0__DM__MASK 0x38000u
#define Drive_Right_MCU__0__DM__SHIFT 15
#define Drive_Right_MCU__0__DR CYREG_PRT1_DR
#define Drive_Right_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Drive_Right_MCU__0__HSIOM_MASK 0x00F00000u
#define Drive_Right_MCU__0__HSIOM_SHIFT 20u
#define Drive_Right_MCU__0__INTCFG CYREG_PRT1_INTCFG
#define Drive_Right_MCU__0__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Right_MCU__0__MASK 0x20u
#define Drive_Right_MCU__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Right_MCU__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Right_MCU__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Right_MCU__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Right_MCU__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Right_MCU__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Right_MCU__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Right_MCU__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Right_MCU__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Right_MCU__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Right_MCU__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Right_MCU__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Right_MCU__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Right_MCU__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Right_MCU__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Right_MCU__0__PC CYREG_PRT1_PC
#define Drive_Right_MCU__0__PC2 CYREG_PRT1_PC2
#define Drive_Right_MCU__0__PORT 1u
#define Drive_Right_MCU__0__PS CYREG_PRT1_PS
#define Drive_Right_MCU__0__SHIFT 5
#define Drive_Right_MCU__DR CYREG_PRT1_DR
#define Drive_Right_MCU__INTCFG CYREG_PRT1_INTCFG
#define Drive_Right_MCU__INTSTAT CYREG_PRT1_INTSTAT
#define Drive_Right_MCU__MASK 0x20u
#define Drive_Right_MCU__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Drive_Right_MCU__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Drive_Right_MCU__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Drive_Right_MCU__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Drive_Right_MCU__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Drive_Right_MCU__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Drive_Right_MCU__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Drive_Right_MCU__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Drive_Right_MCU__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Drive_Right_MCU__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Drive_Right_MCU__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Drive_Right_MCU__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Drive_Right_MCU__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Drive_Right_MCU__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Drive_Right_MCU__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Drive_Right_MCU__PC CYREG_PRT1_PC
#define Drive_Right_MCU__PC2 CYREG_PRT1_PC2
#define Drive_Right_MCU__PORT 1u
#define Drive_Right_MCU__PS CYREG_PRT1_PS
#define Drive_Right_MCU__SHIFT 5

/* INPUT_SELECT */
#define INPUT_SELECT__0__DM__MASK 0xE00000u
#define INPUT_SELECT__0__DM__SHIFT 21
#define INPUT_SELECT__0__DR CYREG_PRT1_DR
#define INPUT_SELECT__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define INPUT_SELECT__0__HSIOM_MASK 0xF0000000u
#define INPUT_SELECT__0__HSIOM_SHIFT 28u
#define INPUT_SELECT__0__INTCFG CYREG_PRT1_INTCFG
#define INPUT_SELECT__0__INTSTAT CYREG_PRT1_INTSTAT
#define INPUT_SELECT__0__MASK 0x80u
#define INPUT_SELECT__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define INPUT_SELECT__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define INPUT_SELECT__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define INPUT_SELECT__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define INPUT_SELECT__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define INPUT_SELECT__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define INPUT_SELECT__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define INPUT_SELECT__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define INPUT_SELECT__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define INPUT_SELECT__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define INPUT_SELECT__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define INPUT_SELECT__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define INPUT_SELECT__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define INPUT_SELECT__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define INPUT_SELECT__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define INPUT_SELECT__0__PC CYREG_PRT1_PC
#define INPUT_SELECT__0__PC2 CYREG_PRT1_PC2
#define INPUT_SELECT__0__PORT 1u
#define INPUT_SELECT__0__PS CYREG_PRT1_PS
#define INPUT_SELECT__0__SHIFT 7
#define INPUT_SELECT__DR CYREG_PRT1_DR
#define INPUT_SELECT__INTCFG CYREG_PRT1_INTCFG
#define INPUT_SELECT__INTSTAT CYREG_PRT1_INTSTAT
#define INPUT_SELECT__MASK 0x80u
#define INPUT_SELECT__PA__CFG0 CYREG_UDB_PA1_CFG0
#define INPUT_SELECT__PA__CFG1 CYREG_UDB_PA1_CFG1
#define INPUT_SELECT__PA__CFG10 CYREG_UDB_PA1_CFG10
#define INPUT_SELECT__PA__CFG11 CYREG_UDB_PA1_CFG11
#define INPUT_SELECT__PA__CFG12 CYREG_UDB_PA1_CFG12
#define INPUT_SELECT__PA__CFG13 CYREG_UDB_PA1_CFG13
#define INPUT_SELECT__PA__CFG14 CYREG_UDB_PA1_CFG14
#define INPUT_SELECT__PA__CFG2 CYREG_UDB_PA1_CFG2
#define INPUT_SELECT__PA__CFG3 CYREG_UDB_PA1_CFG3
#define INPUT_SELECT__PA__CFG4 CYREG_UDB_PA1_CFG4
#define INPUT_SELECT__PA__CFG5 CYREG_UDB_PA1_CFG5
#define INPUT_SELECT__PA__CFG6 CYREG_UDB_PA1_CFG6
#define INPUT_SELECT__PA__CFG7 CYREG_UDB_PA1_CFG7
#define INPUT_SELECT__PA__CFG8 CYREG_UDB_PA1_CFG8
#define INPUT_SELECT__PA__CFG9 CYREG_UDB_PA1_CFG9
#define INPUT_SELECT__PC CYREG_PRT1_PC
#define INPUT_SELECT__PC2 CYREG_PRT1_PC2
#define INPUT_SELECT__PORT 1u
#define INPUT_SELECT__PS CYREG_PRT1_PS
#define INPUT_SELECT__SHIFT 7

/* Miscellaneous */
#define CY_VERSION "PSoC Creator  3.1 SP1"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 6u
#define CYDEV_CHIP_DIE_PSOC4A 3u
#define CYDEV_CHIP_DIE_PSOC5LP 5u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 3u
#define CYDEV_CHIP_MEMBER_4D 2u
#define CYDEV_CHIP_MEMBER_4F 4u
#define CYDEV_CHIP_MEMBER_5A 6u
#define CYDEV_CHIP_MEMBER_5B 5u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0400
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
